services:
  app:
    build: .
    container_name: node_app
    volumes:
      - .:/app # 🔥 live code sync
    command: npm run dev # or nodemon
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cohort
      - NODE_ENV=development

  mongo:
    image: mongo:8
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_8:/data/db

volumes:
  mongo_data_8:
